const station_ids = {
    "Abbey Wood": ['910GABWDXR'],
    "Acton Main Line": ['910GACTONML'],
    "Acton Town": ['940GZZLUACT'],
    "Aldgate": ['940GZZLUALD'],
    "Aldgate East": ['940GZZLUADE'],
    "Alperton": ['940GZZLUALP'],
    "Amersham": ['940GZZLUAMS'],
    "Angel": ['940GZZLUAGL'],
    "Archway": ['940GZZLUACY'],
    "Arnos Grove": ['940GZZLUASG'],
    "Arsenal": ['940GZZLUASL'],
    "Baker Street": ['940GZZLUBST'],
    "Balham": ['940GZZLUBLM'],
    "Bank": ['940GZZLUBNK'],
    "Barbican": ['940GZZLUBBN'],
    "Barking": ['940GZZLUBKG'],
    "Barkingside": ['940GZZLUBKE'],
    "Barons Court": ['940GZZLUBSC'],
    "Bayswater": ['940GZZLUBWT'],
    "Becontree": ['940GZZLUBEC'],
    "Belsize Park": ['940GZZLUBZP'],
    "Bermondsey": ['940GZZLUBMY'],
    "Bethnal Green": ['940GZZLUBLG'],
    "Blackfriars": ['940GZZLUBKF'],
    "Blackhorse Road": ['940GZZLUBLR'],
    "Bond Street": ['910GBONDST', '940GZZLUBND'],
    "Borough": ['940GZZLUBOR'],
    "Boston Manor": ['940GZZLUBOS'],
    "Bounds Green": ['940GZZLUBDS'],
    "Bow Road": ['940GZZLUBWR'],
    "Brent Cross": ['940GZZLUBTX'],
    "Brentwood": ['910GBRTWOOD'],
    "Brixton": ['940GZZLUBXN'],
    "Bromley-by-Bow": ['940GZZLUBBB'],
    "Buckhurst Hill": ['940GZZLUBKH'],
    "Burnham (Berks)": ['910GBNHAM'],
    "Burnt Oak": ['940GZZLUBTK'],
    "Caledonian Road": ['940GZZLUCAR'],
    "Camden Town": ['940GZZLUCTN'],
    "Canada Water": ['940GZZLUCWR'],
    "Canary Wharf": ['910GCANWHRF', '940GZZLUCYF'],        
    "Canning Town": ['940GZZLUCGT'],
    "Cannon Street": ['940GZZLUCST'],
    "Canons Park": ['940GZZLUCPK'],
    "Chadwell Heath": ['910GCHDWLHT'],
    "Chalfont & Latimer": ['940GZZLUCAL'],
    "Chalk Farm": ['940GZZLUCFM'],
    "Chancery Lane": ['940GZZLUCHL'],
    "Charing Cross": ['940GZZLUCHX'],
    "Chesham": ['940GZZLUCSM'],
    "Chigwell": ['940GZZLUCWL'],
    "Chiswick Park": ['940GZZLUCWP'],
    "Chorleywood": ['940GZZLUCYD'],
    "Clapham Common": ['940GZZLUCPC'],
    "Clapham North": ['940GZZLUCPN'],
    "Clapham South": ['940GZZLUCPS'],
    "Cockfosters": ['940GZZLUCKS'],
    "Colindale": ['940GZZLUCND'],
    "Colliers Wood": ['940GZZLUCSD'],
    "Covent Garden": ['940GZZLUCGN'],
    "Croxley": ['940GZZLUCXY'],
    "Custom House": ['910GCSTMHSXR'],
    "Dagenham East": ['940GZZLUDGE'],
    "Dagenham Heathway": ['940GZZLUDGY'],
    "Debden": ['940GZZLUDBN'],
    "Dollis Hill": ['940GZZLUDOH'],
    "Ealing Broadway": ['910GEALINGB', '940GZZLUEBY'],     
    "Ealing Common": ['940GZZLUECM'],
    "Earl's Court": ['940GZZLUECT'],
    "East Acton": ['940GZZLUEAN'],
    "East Finchley": ['940GZZLUEFY'],
    "East Ham": ['940GZZLUEHM'],
    "East Putney": ['940GZZLUEPY'],
    "Eastcote": ['940GZZLUEAE'],
    "Edgware": ['940GZZLUEGW'],
    "Edgware Road": ['940GZZLUERB', '940GZZLUERC'],        
    "Elephant & Castle": ['940GZZLUEAC'],
    "Elm Park": ['940GZZLUEPK'],
    "Embankment": ['940GZZLUEMB'],
    "Epping": ['940GZZLUEPG'],
    "Euston": ['940GZZLUEUS'],
    "Euston Square": ['940GZZLUESQ'],
    "Fairlop": ['940GZZLUFLP'],
    "Farringdon": ['910GFRNDXR', '940GZZLUFCN'],
    "Finchley Central": ['940GZZLUFYC'],
    "Finchley Road": ['940GZZLUFYR'],
    "Finsbury Park": ['940GZZLUFPK'],
    "Forest Gate": ['910GFRSTGT'],
    "Fulham Broadway": ['940GZZLUFBY'],
    "Gants Hill": ['940GZZLUGTH'],
    "Gidea Park": ['910GGIDEAPK'],
    "Gloucester Road": ['940GZZLUGTR'],
    "Golders Green": ['940GZZLUGGN'],
    "Goldhawk Road": ['940GZZLUGHK'],
    "Goodge Street": ['940GZZLUGDG'],
    "Goodmayes": ['910GGODMAYS'],
    "Grange Hill": ['940GZZLUGGH'],
    "Great Portland Street": ['940GZZLUGPS'],
    "Green Park": ['940GZZLUGPK'],
    "Greenford": ['940GZZLUGFD'],
    "Gunnersbury": ['940GZZLUGBY'],
    "Hainault": ['940GZZLUHLT'],
    "Hammersmith": ['940GZZLUHSD', '940GZZLUHSC'],
    "Hampstead": ['940GZZLUHTD'],
    "Hanger Lane": ['940GZZLUHGR'],
    "Hanwell": ['910GHANWELL'],
    "Harlesden": ['940GZZLUHSN'],
    "Harold Wood": ['910GHRLDWOD'],
    "Harrow & Wealdstone": ['940GZZLUHAW'],
    "Harrow-on-the-Hill": ['940GZZLUHOH'],
    "Hatton Cross": ['940GZZLUHNX'],
    "Hayes & Harlington": ['910GHAYESAH'],
    "Heathrow Terminal 4": ['910GHTRWTM4', '940GZZLUHR4'], 
    "Heathrow Terminal 5": ['910GHTRWTM5', '940GZZLUHR5'], 
    "Heathrow Terminals 2 & 3": ['910GHTRWAPT', '940GZZLUHRC'],
    "Hendon Central": ['940GZZLUHCL'],
    "High Barnet": ['940GZZLUHBT'],
    "High Street Kensington": ['940GZZLUHSK'],
    "Highbury & Islington": ['940GZZLUHAI'],
    "Highgate": ['940GZZLUHGT'],
    "Hillingdon": ['940GZZLUHGD'],
    "Holborn": ['940GZZLUHBN'],
    "Holland Park": ['940GZZLUHPK'],
    "Holloway Road": ['940GZZLUHWY'],
    "Hornchurch": ['940GZZLUHCH'],
    "Hounslow Central": ['940GZZLUHWC'],
    "Hounslow East": ['940GZZLUHWE'],
    "Hounslow West": ['940GZZLUHWT'],
    "Hyde Park Corner": ['940GZZLUHPC'],
    "Ickenham": ['940GZZLUICK'],
    "Ilford": ['910GILFORD'],
    "Iver": ['910GIVER'],
    "Kennington": ['940GZZLUKNG'],
    "Kensal Green": ['940GZZLUKSL'],
    "Kensington (Olympia)": ['940GZZLUKOY'],
    "Kentish Town": ['940GZZLUKSH'],
    "Kenton": ['940GZZLUKEN'],
    "Kew Gardens": ['940GZZLUKWG'],
    "Kilburn": ['940GZZLUKBN'],
    "Kilburn Park": ['940GZZLUKPK'],
    "King's Cross St. Pancras": ['940GZZLUKSX'],
    "Kingsbury": ['940GZZLUKBY'],
    "Knightsbridge": ['940GZZLUKNB'],
    "Ladbroke Grove": ['940GZZLULAD'],
    "Lambeth North": ['940GZZLULBN'],
    "Lancaster Gate": ['940GZZLULGT'],
    "Langley (Berks)": ['910GLANGLEY'],
    "Latimer Road": ['940GZZLULRD'],
    "Leicester Square": ['940GZZLULSQ'],
    "Leyton": ['940GZZLULYN'],
    "Leytonstone": ['940GZZLULYS'],
    "Liverpool Street": ['910GLIVSTLL', '940GZZLULVT'],    
    "London Bridge": ['940GZZLULNB'],
    "London Liverpool Street": ['910GLIVST'],
    "Loughton": ['940GZZLULGN'],
    "Maidenhead": ['910GMDNHEAD'],
    "Manor House": ['940GZZLUMRH'],
    "Manor Park": ['910GMANRPK'],
    "Mansion House": ['940GZZLUMSH'],
    "Marble Arch": ['940GZZLUMBA'],
    "Maryland": ['910GMRYLAND'],
    "Marylebone": ['940GZZLUMYB'],
    "Mile End": ['940GZZLUMED'],
    "Mill Hill East": ['940GZZLUMHL'],
    "Monument": ['940GZZLUMMT'],
    "Moor Park": ['940GZZLUMPK'],
    "Moorgate": ['940GZZLUMGT'],
    "Morden": ['940GZZLUMDN'],
    "Mornington Crescent": ['940GZZLUMTC'],
    "Neasden": ['940GZZLUNDN'],
    "Newbury Park": ['940GZZLUNBP'],
    "North Acton": ['940GZZLUNAN'],
    "North Ealing": ['940GZZLUNEN'],
    "North Greenwich": ['940GZZLUNGW'],
    "North Harrow": ['940GZZLUNHA'],
    "North Wembley": ['940GZZLUNWY'],
    "Northfields": ['940GZZLUNFD'],
    "Northolt": ['940GZZLUNHT'],
    "Northwick Park": ['940GZZLUNKP'],
    "Northwood": ['940GZZLUNOW'],
    "Northwood Hills": ['940GZZLUNWH'],
    "Notting Hill Gate": ['940GZZLUNHG'],
    "Oakwood": ['940GZZLUOAK'],
    "Old Street": ['940GZZLUODS'],
    "Osterley": ['940GZZLUOSY'],
    "Oval": ['940GZZLUOVL'],
    "Oxford Circus": ['940GZZLUOXC'],
    "Paddington": ['910GPADTLL', '910GPADTON', '940GZZLUPAC', '940GZZLUPAH'],
    "Park Royal": ['940GZZLUPKR'],
    "Parsons Green": ['940GZZLUPSG'],
    "Perivale": ['940GZZLUPVL'],
    "Piccadilly Circus": ['940GZZLUPCC'],
    "Pimlico": ['940GZZLUPCO'],
    "Pinner": ['940GZZLUPNR'],
    "Plaistow": ['940GZZLUPLW'],
    "Preston Road": ['940GZZLUPRD'],
    "Putney Bridge": ['940GZZLUPYB'],
    "Queen's Park": ['940GZZLUQPS'],
    "Queensbury": ['940GZZLUQBY'],
    "Queensway": ['940GZZLUQWY'],
    "Ravenscourt Park": ['940GZZLURVP'],
    "Rayners Lane": ['940GZZLURYL'],
    "Reading": ['910GRDNGSTN'],
    "Redbridge": ['940GZZLURBG'],
    "Regent's Park": ['940GZZLURGP'],
    "Richmond": ['940GZZLURMD'],
    "Rickmansworth": ['940GZZLURKW'],
    "Roding Valley": ['940GZZLURVY'],
    "Romford": ['910GROMFORD'],
    "Royal Oak": ['940GZZLURYO'],
    "Ruislip": ['940GZZLURSP'],
    "Ruislip Gardens": ['940GZZLURSG'],
    "Ruislip Manor": ['940GZZLURSM'],
    "Russell Square": ['940GZZLURSQ'],
    "Seven Kings": ['910GSVNKNGS'],
    "Seven Sisters": ['940GZZLUSVS'],
    "Shenfield": ['910GSHENFLD'],
    "Shepherd's Bush": ['940GZZLUSBC'],
    "Shepherd's Bush Market": ['940GZZLUSBM'],
    "Sloane Square": ['940GZZLUSSQ'],
    "Slough": ['910GSLOUGH'],
    "Snaresbrook": ['940GZZLUSNB'],
    "South Ealing": ['940GZZLUSEA'],
    "South Harrow": ['940GZZLUSHH'],
    "South Kensington": ['940GZZLUSKS'],
    "South Kenton": ['940GZZLUSKT'],
    "South Ruislip": ['940GZZLUSRP'],
    "South Wimbledon": ['940GZZLUSWN'],
    "South Woodford": ['940GZZLUSWF'],
    "Southall": ['910GSTHALL'],
    "Southfields": ['940GZZLUSFS'],
    "Southgate": ['940GZZLUSGT'],
    "Southwark": ['940GZZLUSWK'],
    "St. James's Park": ['940GZZLUSJP'],
    "St. John's Wood": ['940GZZLUSJW'],
    "St. Paul's": ['940GZZLUSPU'],
    "Stamford Brook": ['940GZZLUSFB'],
    "Stanmore": ['940GZZLUSTM'],
    "Stepney Green": ['940GZZLUSGN'],
    "Stockwell": ['940GZZLUSKW'],
    "Stonebridge Park": ['940GZZLUSGP'],
    "Stratford": ['940GZZLUSTD',"910GSTFD"],
    "Sudbury Hill": ['940GZZLUSUH'],
    "Sudbury Town": ['940GZZLUSUT'],
    "Swiss Cottage": ['940GZZLUSWC'],
    "Taplow": ['910GTAPLOW'],
    "Temple": ['940GZZLUTMP'],
    "Theydon Bois": ['940GZZLUTHB'],
    "Tooting Bec": ['940GZZLUTBC'],
    "Tooting Broadway": ['940GZZLUTBY'],
    "Tottenham Court Road": ['910GTOTCTRD', '940GZZLUTCR'],
    "Tottenham Hale": ['940GZZLUTMH'],
    "Totteridge & Whetstone": ['940GZZLUTAW'],
    "Tower Hill": ['940GZZLUTWH'],
    "Tufnell Park": ['940GZZLUTFP'],
    "Turnham Green": ['940GZZLUTNG'],
    "Turnpike Lane": ['940GZZLUTPN'],
    "Twyford": ['910GTWYFORD'],
    "Upminster": ['940GZZLUUPM'],
    "Upminster Bridge": ['940GZZLUUPB'],
    "Upney": ['940GZZLUUPY'],
    "Upton Park": ['940GZZLUUPK'],
    "Uxbridge": ['940GZZLUUXB'],
    "Vauxhall": ['940GZZLUVXL'],
    "Victoria": ['940GZZLUVIC'],
    "Walthamstow Central": ['940GZZLUWWL'],
    "Wanstead": ['940GZZLUWSD'],
    "Warren Street": ['940GZZLUWRR'],
    "Warwick Avenue": ['940GZZLUWKA'],
    "Waterloo": ['940GZZLUWLO'],
    "Watford": ['940GZZLUWAF'],
    "Wembley Central": ['940GZZLUWYC'],
    "Wembley Park": ['940GZZLUWYP'],
    "West Acton": ['940GZZLUWTA'],
    "West Brompton": ['940GZZLUWBN'],
    "West Drayton": ['910GWDRYTON'],
    "West Ealing": ['910GWEALING'],
    "West Finchley": ['940GZZLUWFN'],
    "West Ham": ['940GZZLUWHM'],
    "West Hampstead": ['940GZZLUWHP'],
    "West Harrow": ['940GZZLUWHW'],
    "West Kensington": ['940GZZLUWKN'],
    "West Ruislip": ['940GZZLUWRP'],
    "Westbourne Park": ['940GZZLUWSP'],
    "Westminster": ['940GZZLUWSM'],
    "White City": ['940GZZLUWCY'],
    "Whitechapel": ['910GWCHAPXR', '940GZZLUWPL'],
    "Willesden Green": ['940GZZLUWIG'],
    "Willesden Junction": ['940GZZLUWJN'],
    "Wimbledon": ['940GZZLUWIM'],
    "Wimbledon Park": ['940GZZLUWIP'],
    "Wood Green": ['940GZZLUWOG'],
    "Wood Lane": ['940GZZLUWLA'],
    "Woodford": ['940GZZLUWOF'],
    "Woodside Park": ['940GZZLUWOP'],
    "Woolwich": ['910GWOLWXR'],
};
